
package multas_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiciosMultaService", targetNamespace = "http://multas_service/", wsdlLocation = "http://localhost:8080/Multas_Web/ServiciosMulta?wsdl")
public class ServiciosMultaService
    extends Service
{

    private final static URL SERVICIOSMULTASERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOSMULTASERVICE_EXCEPTION;
    private final static QName SERVICIOSMULTASERVICE_QNAME = new QName("http://multas_service/", "ServiciosMultaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Multas_Web/ServiciosMulta?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOSMULTASERVICE_WSDL_LOCATION = url;
        SERVICIOSMULTASERVICE_EXCEPTION = e;
    }

    public ServiciosMultaService() {
        super(__getWsdlLocation(), SERVICIOSMULTASERVICE_QNAME);
    }

    public ServiciosMultaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOSMULTASERVICE_QNAME, features);
    }

    public ServiciosMultaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOSMULTASERVICE_QNAME);
    }

    public ServiciosMultaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOSMULTASERVICE_QNAME, features);
    }

    public ServiciosMultaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosMultaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiciosMulta
     */
    @WebEndpoint(name = "ServiciosMultaPort")
    public ServiciosMulta getServiciosMultaPort() {
        return super.getPort(new QName("http://multas_service/", "ServiciosMultaPort"), ServiciosMulta.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiciosMulta
     */
    @WebEndpoint(name = "ServiciosMultaPort")
    public ServiciosMulta getServiciosMultaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://multas_service/", "ServiciosMultaPort"), ServiciosMulta.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOSMULTASERVICE_EXCEPTION!= null) {
            throw SERVICIOSMULTASERVICE_EXCEPTION;
        }
        return SERVICIOSMULTASERVICE_WSDL_LOCATION;
    }

}
