
package api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MultasServiceService", targetNamespace = "http://api/", wsdlLocation = "http://192.168.1.139:8080/MultasWebService?wsdl")
public class MultasServiceService
    extends Service
{

    private final static URL MULTASSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MULTASSERVICESERVICE_EXCEPTION;
    private final static QName MULTASSERVICESERVICE_QNAME = new QName("http://api/", "MultasServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.139:8080/MultasWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MULTASSERVICESERVICE_WSDL_LOCATION = url;
        MULTASSERVICESERVICE_EXCEPTION = e;
    }

    public MultasServiceService() {
        super(__getWsdlLocation(), MULTASSERVICESERVICE_QNAME);
    }

    public MultasServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MULTASSERVICESERVICE_QNAME, features);
    }

    public MultasServiceService(URL wsdlLocation) {
        super(wsdlLocation, MULTASSERVICESERVICE_QNAME);
    }

    public MultasServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MULTASSERVICESERVICE_QNAME, features);
    }

    public MultasServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultasServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MultasService
     */
    @WebEndpoint(name = "MultasServicePort")
    public MultasService getMultasServicePort() {
        return super.getPort(new QName("http://api/", "MultasServicePort"), MultasService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MultasService
     */
    @WebEndpoint(name = "MultasServicePort")
    public MultasService getMultasServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api/", "MultasServicePort"), MultasService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MULTASSERVICESERVICE_EXCEPTION!= null) {
            throw MULTASSERVICESERVICE_EXCEPTION;
        }
        return MULTASSERVICESERVICE_WSDL_LOCATION;
    }

}
