
package lib;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PropietarioMultaImpService", targetNamespace = "http://lib/", wsdlLocation = "http://localhost:8080/sca_webimplementation/PropietarioMultaImp?wsdl")
public class PropietarioMultaImpService
    extends Service
{

    private final static URL PROPIETARIOMULTAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROPIETARIOMULTAIMPSERVICE_EXCEPTION;
    private final static QName PROPIETARIOMULTAIMPSERVICE_QNAME = new QName("http://lib/", "PropietarioMultaImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sca_webimplementation/PropietarioMultaImp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROPIETARIOMULTAIMPSERVICE_WSDL_LOCATION = url;
        PROPIETARIOMULTAIMPSERVICE_EXCEPTION = e;
    }

    public PropietarioMultaImpService() {
        super(__getWsdlLocation(), PROPIETARIOMULTAIMPSERVICE_QNAME);
    }

    public PropietarioMultaImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROPIETARIOMULTAIMPSERVICE_QNAME, features);
    }

    public PropietarioMultaImpService(URL wsdlLocation) {
        super(wsdlLocation, PROPIETARIOMULTAIMPSERVICE_QNAME);
    }

    public PropietarioMultaImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROPIETARIOMULTAIMPSERVICE_QNAME, features);
    }

    public PropietarioMultaImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropietarioMultaImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PropietarioMultaImp
     */
    @WebEndpoint(name = "PropietarioMultaImpPort")
    public PropietarioMultaImp getPropietarioMultaImpPort() {
        return super.getPort(new QName("http://lib/", "PropietarioMultaImpPort"), PropietarioMultaImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropietarioMultaImp
     */
    @WebEndpoint(name = "PropietarioMultaImpPort")
    public PropietarioMultaImp getPropietarioMultaImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lib/", "PropietarioMultaImpPort"), PropietarioMultaImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROPIETARIOMULTAIMPSERVICE_EXCEPTION!= null) {
            throw PROPIETARIOMULTAIMPSERVICE_EXCEPTION;
        }
        return PROPIETARIOMULTAIMPSERVICE_WSDL_LOCATION;
    }

}
