
package extravalservice.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AOS_Extraval_EstadoAvalesCliente", targetNamespace = "http://endpoint.extravalservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AOSExtravalEstadoAvalesCliente {


    /**
     * 
     * @param arg0
     * @return
     *     returns extravalservice.endpoint.ArrayOfSolicitud
     */
    @WebMethod
    @WebResult(name = "solicitudAvales", targetNamespace = "")
    @RequestWrapper(localName = "solicitudAvalesDeUnCliente", targetNamespace = "http://endpoint.extravalservice/", className = "extravalservice.endpoint.SolicitudAvalesDeUnCliente")
    @ResponseWrapper(localName = "solicitudAvalesDeUnClienteResponse", targetNamespace = "http://endpoint.extravalservice/", className = "extravalservice.endpoint.SolicitudAvalesDeUnClienteResponse")
    public ArrayOfSolicitud solicitudAvalesDeUnCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
