
package extravalservice.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AOS_Extraval_FormalizarReciboParticipacionesSocioService", targetNamespace = "http://endpoint.extravalservice/", wsdlLocation = "http://localhost:8080/wildfly_jaxws_extravalservices/AOS_Extraval_FormalizarReciboParticipacionesSocio?wsdl")
public class AOSExtravalFormalizarReciboParticipacionesSocioService
    extends Service
{

    private final static URL AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_EXCEPTION;
    private final static QName AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_QNAME = new QName("http://endpoint.extravalservice/", "AOS_Extraval_FormalizarReciboParticipacionesSocioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wildfly_jaxws_extravalservices/AOS_Extraval_FormalizarReciboParticipacionesSocio?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_WSDL_LOCATION = url;
        AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_EXCEPTION = e;
    }

    public AOSExtravalFormalizarReciboParticipacionesSocioService() {
        super(__getWsdlLocation(), AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_QNAME);
    }

    public AOSExtravalFormalizarReciboParticipacionesSocioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_QNAME, features);
    }

    public AOSExtravalFormalizarReciboParticipacionesSocioService(URL wsdlLocation) {
        super(wsdlLocation, AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_QNAME);
    }

    public AOSExtravalFormalizarReciboParticipacionesSocioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_QNAME, features);
    }

    public AOSExtravalFormalizarReciboParticipacionesSocioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AOSExtravalFormalizarReciboParticipacionesSocioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AOSExtravalFormalizarReciboParticipacionesSocio
     */
    @WebEndpoint(name = "AOS_Extraval_FormalizarReciboParticipacionesSocioPort")
    public AOSExtravalFormalizarReciboParticipacionesSocio getAOSExtravalFormalizarReciboParticipacionesSocioPort() {
        return super.getPort(new QName("http://endpoint.extravalservice/", "AOS_Extraval_FormalizarReciboParticipacionesSocioPort"), AOSExtravalFormalizarReciboParticipacionesSocio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AOSExtravalFormalizarReciboParticipacionesSocio
     */
    @WebEndpoint(name = "AOS_Extraval_FormalizarReciboParticipacionesSocioPort")
    public AOSExtravalFormalizarReciboParticipacionesSocio getAOSExtravalFormalizarReciboParticipacionesSocioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.extravalservice/", "AOS_Extraval_FormalizarReciboParticipacionesSocioPort"), AOSExtravalFormalizarReciboParticipacionesSocio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_EXCEPTION!= null) {
            throw AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_EXCEPTION;
        }
        return AOSEXTRAVALFORMALIZARRECIBOPARTICIPACIONESSOCIOSERVICE_WSDL_LOCATION;
    }

}
