
package extravalservice.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AOS_Extraval_AprovacionAvalCliente", targetNamespace = "http://endpoint.extravalservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AOSExtravalAprovacionAvalCliente {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns extravalservice.endpoint.CambiarEstadoAvalDeUnClienteResponse.SolicitudAvalACambiar
     */
    @WebMethod
    @WebResult(name = "solicitudAvalACambiar", targetNamespace = "")
    @RequestWrapper(localName = "cambiarEstadoAvalDeUnCliente", targetNamespace = "http://endpoint.extravalservice/", className = "extravalservice.endpoint.CambiarEstadoAvalDeUnCliente")
    @ResponseWrapper(localName = "cambiarEstadoAvalDeUnClienteResponse", targetNamespace = "http://endpoint.extravalservice/", className = "extravalservice.endpoint.CambiarEstadoAvalDeUnClienteResponse")
    public extravalservice.endpoint.CambiarEstadoAvalDeUnClienteResponse.SolicitudAvalACambiar cambiarEstadoAvalDeUnCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
