
package extravalservice.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AOS_Extraval_EstadoAvalesClienteService", targetNamespace = "http://endpoint.extravalservice/", wsdlLocation = "http://localhost:8080/wildfly_jaxws_extravalservices/AOS_Extraval_EstadoAvalesCliente?wsdl")
public class AOSExtravalEstadoAvalesClienteService
    extends Service
{

    private final static URL AOSEXTRAVALESTADOAVALESCLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException AOSEXTRAVALESTADOAVALESCLIENTESERVICE_EXCEPTION;
    private final static QName AOSEXTRAVALESTADOAVALESCLIENTESERVICE_QNAME = new QName("http://endpoint.extravalservice/", "AOS_Extraval_EstadoAvalesClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wildfly_jaxws_extravalservices/AOS_Extraval_EstadoAvalesCliente?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AOSEXTRAVALESTADOAVALESCLIENTESERVICE_WSDL_LOCATION = url;
        AOSEXTRAVALESTADOAVALESCLIENTESERVICE_EXCEPTION = e;
    }

    public AOSExtravalEstadoAvalesClienteService() {
        super(__getWsdlLocation(), AOSEXTRAVALESTADOAVALESCLIENTESERVICE_QNAME);
    }

    public AOSExtravalEstadoAvalesClienteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AOSEXTRAVALESTADOAVALESCLIENTESERVICE_QNAME, features);
    }

    public AOSExtravalEstadoAvalesClienteService(URL wsdlLocation) {
        super(wsdlLocation, AOSEXTRAVALESTADOAVALESCLIENTESERVICE_QNAME);
    }

    public AOSExtravalEstadoAvalesClienteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AOSEXTRAVALESTADOAVALESCLIENTESERVICE_QNAME, features);
    }

    public AOSExtravalEstadoAvalesClienteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AOSExtravalEstadoAvalesClienteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AOSExtravalEstadoAvalesCliente
     */
    @WebEndpoint(name = "AOS_Extraval_EstadoAvalesClientePort")
    public AOSExtravalEstadoAvalesCliente getAOSExtravalEstadoAvalesClientePort() {
        return super.getPort(new QName("http://endpoint.extravalservice/", "AOS_Extraval_EstadoAvalesClientePort"), AOSExtravalEstadoAvalesCliente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AOSExtravalEstadoAvalesCliente
     */
    @WebEndpoint(name = "AOS_Extraval_EstadoAvalesClientePort")
    public AOSExtravalEstadoAvalesCliente getAOSExtravalEstadoAvalesClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.extravalservice/", "AOS_Extraval_EstadoAvalesClientePort"), AOSExtravalEstadoAvalesCliente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AOSEXTRAVALESTADOAVALESCLIENTESERVICE_EXCEPTION!= null) {
            throw AOSEXTRAVALESTADOAVALESCLIENTESERVICE_EXCEPTION;
        }
        return AOSEXTRAVALESTADOAVALESCLIENTESERVICE_WSDL_LOCATION;
    }

}
