
package extravalservice.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AOS_Extraval_AprovacionAvalClienteService", targetNamespace = "http://endpoint.extravalservice/", wsdlLocation = "http://localhost:8080/wildfly_jaxws_extravalservices/AOS_Extraval_AprovacionAvalCliente?wsdl")
public class AOSExtravalAprovacionAvalClienteService
    extends Service
{

    private final static URL AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_EXCEPTION;
    private final static QName AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_QNAME = new QName("http://endpoint.extravalservice/", "AOS_Extraval_AprovacionAvalClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wildfly_jaxws_extravalservices/AOS_Extraval_AprovacionAvalCliente?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_WSDL_LOCATION = url;
        AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_EXCEPTION = e;
    }

    public AOSExtravalAprovacionAvalClienteService() {
        super(__getWsdlLocation(), AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_QNAME);
    }

    public AOSExtravalAprovacionAvalClienteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_QNAME, features);
    }

    public AOSExtravalAprovacionAvalClienteService(URL wsdlLocation) {
        super(wsdlLocation, AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_QNAME);
    }

    public AOSExtravalAprovacionAvalClienteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_QNAME, features);
    }

    public AOSExtravalAprovacionAvalClienteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AOSExtravalAprovacionAvalClienteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AOSExtravalAprovacionAvalCliente
     */
    @WebEndpoint(name = "AOS_Extraval_AprovacionAvalClientePort")
    public AOSExtravalAprovacionAvalCliente getAOSExtravalAprovacionAvalClientePort() {
        return super.getPort(new QName("http://endpoint.extravalservice/", "AOS_Extraval_AprovacionAvalClientePort"), AOSExtravalAprovacionAvalCliente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AOSExtravalAprovacionAvalCliente
     */
    @WebEndpoint(name = "AOS_Extraval_AprovacionAvalClientePort")
    public AOSExtravalAprovacionAvalCliente getAOSExtravalAprovacionAvalClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.extravalservice/", "AOS_Extraval_AprovacionAvalClientePort"), AOSExtravalAprovacionAvalCliente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_EXCEPTION!= null) {
            throw AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_EXCEPTION;
        }
        return AOSEXTRAVALAPROVACIONAVALCLIENTESERVICE_WSDL_LOCATION;
    }

}
