
package multas_service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiciosMulta", targetNamespace = "http://multas_service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiciosMulta {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaMulta", targetNamespace = "http://multas_service/", className = "multas_service.ConsultaMulta")
    @ResponseWrapper(localName = "consultaMultaResponse", targetNamespace = "http://multas_service/", className = "multas_service.ConsultaMultaResponse")
    public boolean consultaMulta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param return1
     * @param return0
     * @param return2
     */
    @WebMethod
    @RequestWrapper(localName = "detalleMulta", targetNamespace = "http://multas_service/", className = "multas_service.DetalleMulta")
    @ResponseWrapper(localName = "detalleMultaResponse", targetNamespace = "http://multas_service/", className = "multas_service.DetalleMultaResponse")
    public void detalleMulta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "return0", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> return0,
        @WebParam(name = "return1", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Propietario> return1,
        @WebParam(name = "return2", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Vehiculo> return2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaMultaMeses", targetNamespace = "http://multas_service/", className = "multas_service.ConsultaMultaMeses")
    @ResponseWrapper(localName = "consultaMultaMesesResponse", targetNamespace = "http://multas_service/", className = "multas_service.ConsultaMultaMesesResponse")
    public List<Integer> consultaMultaMeses(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns multas_service.Propietario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "propietarioMulta", targetNamespace = "http://multas_service/", className = "multas_service.PropietarioMulta")
    @ResponseWrapper(localName = "propietarioMultaResponse", targetNamespace = "http://multas_service/", className = "multas_service.PropietarioMultaResponse")
    public Propietario propietarioMulta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
