
package lib;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DetalleMultaImpService", targetNamespace = "http://lib/", wsdlLocation = "http://localhost:8080/sca_webimplementation/DetalleMultaImp?wsdl")
public class DetalleMultaImpService
    extends Service
{

    private final static URL DETALLEMULTAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException DETALLEMULTAIMPSERVICE_EXCEPTION;
    private final static QName DETALLEMULTAIMPSERVICE_QNAME = new QName("http://lib/", "DetalleMultaImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sca_webimplementation/DetalleMultaImp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DETALLEMULTAIMPSERVICE_WSDL_LOCATION = url;
        DETALLEMULTAIMPSERVICE_EXCEPTION = e;
    }

    public DetalleMultaImpService() {
        super(__getWsdlLocation(), DETALLEMULTAIMPSERVICE_QNAME);
    }

    public DetalleMultaImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DETALLEMULTAIMPSERVICE_QNAME, features);
    }

    public DetalleMultaImpService(URL wsdlLocation) {
        super(wsdlLocation, DETALLEMULTAIMPSERVICE_QNAME);
    }

    public DetalleMultaImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DETALLEMULTAIMPSERVICE_QNAME, features);
    }

    public DetalleMultaImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DetalleMultaImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DetalleMultaImp
     */
    @WebEndpoint(name = "DetalleMultaImpPort")
    public DetalleMultaImp getDetalleMultaImpPort() {
        return super.getPort(new QName("http://lib/", "DetalleMultaImpPort"), DetalleMultaImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DetalleMultaImp
     */
    @WebEndpoint(name = "DetalleMultaImpPort")
    public DetalleMultaImp getDetalleMultaImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lib/", "DetalleMultaImpPort"), DetalleMultaImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DETALLEMULTAIMPSERVICE_EXCEPTION!= null) {
            throw DETALLEMULTAIMPSERVICE_EXCEPTION;
        }
        return DETALLEMULTAIMPSERVICE_WSDL_LOCATION;
    }

}
