
package api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MultasService", targetNamespace = "http://api/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MultasService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "detalleMulta", targetNamespace = "http://api/", className = "api.DetalleMulta")
    @ResponseWrapper(localName = "detalleMultaResponse", targetNamespace = "http://api/", className = "api.DetalleMultaResponse")
    public String detalleMulta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaMulta", targetNamespace = "http://api/", className = "api.ConsultaMulta")
    @ResponseWrapper(localName = "consultaMultaResponse", targetNamespace = "http://api/", className = "api.ConsultaMultaResponse")
    public Boolean consultaMulta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "propietarioMulta", targetNamespace = "http://api/", className = "api.PropietarioMulta")
    @ResponseWrapper(localName = "propietarioMultaResponse", targetNamespace = "http://api/", className = "api.PropietarioMultaResponse")
    public String propietarioMulta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
