
package lib;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaMultaImpService", targetNamespace = "http://lib/", wsdlLocation = "http://localhost:8080/sca_webimplementation/ConsultaMultaImp?wsdl")
public class ConsultaMultaImpService
    extends Service
{

    private final static URL CONSULTAMULTAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTAMULTAIMPSERVICE_EXCEPTION;
    private final static QName CONSULTAMULTAIMPSERVICE_QNAME = new QName("http://lib/", "ConsultaMultaImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sca_webimplementation/ConsultaMultaImp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAMULTAIMPSERVICE_WSDL_LOCATION = url;
        CONSULTAMULTAIMPSERVICE_EXCEPTION = e;
    }

    public ConsultaMultaImpService() {
        super(__getWsdlLocation(), CONSULTAMULTAIMPSERVICE_QNAME);
    }

    public ConsultaMultaImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAMULTAIMPSERVICE_QNAME, features);
    }

    public ConsultaMultaImpService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAMULTAIMPSERVICE_QNAME);
    }

    public ConsultaMultaImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAMULTAIMPSERVICE_QNAME, features);
    }

    public ConsultaMultaImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaMultaImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaMultaImp
     */
    @WebEndpoint(name = "ConsultaMultaImpPort")
    public ConsultaMultaImp getConsultaMultaImpPort() {
        return super.getPort(new QName("http://lib/", "ConsultaMultaImpPort"), ConsultaMultaImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaMultaImp
     */
    @WebEndpoint(name = "ConsultaMultaImpPort")
    public ConsultaMultaImp getConsultaMultaImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lib/", "ConsultaMultaImpPort"), ConsultaMultaImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAMULTAIMPSERVICE_EXCEPTION!= null) {
            throw CONSULTAMULTAIMPSERVICE_EXCEPTION;
        }
        return CONSULTAMULTAIMPSERVICE_WSDL_LOCATION;
    }

}
