
package lib;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaMultaImp", targetNamespace = "http://lib/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaMultaImp {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaMulta", targetNamespace = "http://lib/", className = "lib.ConsultaMulta")
    @ResponseWrapper(localName = "consultaMultaResponse", targetNamespace = "http://lib/", className = "lib.ConsultaMultaResponse")
    public boolean consultaMulta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
